### ISSUE TITLE
Building installer

### ISSUE THREAD

**Issue by wrcgator** [martinpaljak/osx-ccid-installer#11]
I have the following installed as directed:  XCode plus libtool, autoconf, automake and pkg-config

autoconf, automake and pkg-config were installed using brew from the command prompt.  XCode and libtool were already installed.

I got the source tree and run make using the command in the instructions:

git clone --recursive https://github.com/martinpaljak/osx-ccid-installer
make -C osx-ccid-installer

However, the make fails.  I know next to nothing about the build tools on OSX which probably why I don't know how to resolve the following issues quickly.  I am hoping for some pointers or a fix if one is required.  Here is the build output:

$ make -C osx-ccid-installer/
git submodule foreach git clean -dfx
Entering 'CCID'
Entering 'libusb'
Removing INSTALL
Removing Makefile.in
Removing aclocal.m4
Removing autom4te.cache/
Removing compile
Removing config.h.in
Removing configure
Removing depcomp
Removing doc/Makefile.in
Removing examples/Makefile.in
Removing install-sh
Removing m4/
Removing missing
git submodule foreach git reset --hard
Entering 'CCID'
HEAD is now at 3da71e2 Release 1.4.25
Entering 'libusb'
HEAD is now at 09e75e9 Release 1.0.21
rm -rf target tmp *.pkg *.dmg
(cd libusb \
	&& ./autogen.sh \
	&& ./configure --prefix=/Users/wrcgator/Downloads/osx-ccid-installer-master/osx-ccid-installer/tmp --disable-dependency-tracking --enable-static --disable-shared \
	&& /Applications/Xcode.app/Contents/Developer/usr/bin/make \
	&& /Applications/Xcode.app/Contents/Developer/usr/bin/make install \
	)
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/local/Cellar/autoconf/2.69/bin/autoconf --force
autoreconf: running: /usr/local/Cellar/autoconf/2.69/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:37: installing './compile'
configure.ac:29: installing './install-sh'
configure.ac:29: installing './missing'
Makefile.am: installing './INSTALL'
examples/Makefile.am: installing './depcomp'
libusb/Makefile.am:5: error: Libtool library used but 'LIBTOOL' is undefined
libusb/Makefile.am:5:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
libusb/Makefile.am:5:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
libusb/Makefile.am:5:   If 'LT_INIT' is in 'configure.ac', make sure
libusb/Makefile.am:5:   its definition is in aclocal's search path.
autoreconf: automake failed with exit status: 1
make: *** [/Users/wrcgator/Downloads/osx-ccid-installer-master/osx-ccid-installer/tmp/lib/libusb-1.0.a] Error 1

**Comment by wrcgator** [comment]
Found solution.

I assumed that after typing 'libtool' at the command prompt and an exe ran, that libtool (as needed to build this project) was enough.

I ran brew install libtool and it installed.

I re-ran the make and it completed successfully.

**Comment by martinpaljak** [comment]
I think it makes sense to give replicable instructions with `brew install`, keeping this open until I get to changing the README. PR-s welcome.

**Comment by wrcgator** [comment]
On a pretty vanilla MacBook Pro (generation 10) i did the following:

installed XCode from the app store.
installed Brew: (thanks to https://www.howtogeek.com/211541/homebrew-for-os-x-easily-installs-desktop-apps-and-terminal-utilities/)

xcode-select --install
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew doctor
brew install caskroom/cask/brew-cask

Then I installed the dependencies in this order:

brew install autoconf
brew install automake
brew install pkg-config
brew install libtool

Then I built the installer:

make -C osx-ccid-installer

Worked.

My end goal is to add our reader to the Info.plist as a solution until our reader submissions make it out to the linux and osx standard distributions.  However, first attempt adding it to supportedreaders.txt was not enough.  Reviewing logs and reading the CCID site to find out why.

Regards

Reid

**Comment by martinpaljak** [comment]
Did you manage adding your reader? I would say that adding reader support should be directed to upstream project, re-building the osx installer itself should be easy and reliably repeatable process. If this is not the case, please re-open.
