### ISSUE TITLE
SSH authentication using NitroKeyPro

### ISSUE THREAD

**Issue by TheMSB** [martinpaljak/osx-ccid-installer#4]
I have been trying to get my NitroKey (OpenPGP Smartcard) to work for SSH authentication
on OSX. Operation for all other applications works fine.

`gpg --card-status` lists the smartcard just fine but using

`ssh <username>@<host>`

yields: 

> Permission denied (publickey,gssapi-keyex,gssapi-with-mic).

Unsure if a bug with the driver.

**Comment by martinpaljak** [comment]
I'm sorry, I don't think that this has anything to do with the CCID driver (at least not with such description)

**Comment by TheMSB** [comment]
I am wondering since I am unsure if I am mistaken in my operation of the smartcard or if it is a bug in the driver.

**Comment by martinpaljak** [comment]
If you see the reader (and the card) this driver has most probably done its job. If you have a _specific_ issue, it would probably belong to the CCID project. But if you have a problem of the token not working with some 3rd party app, it is best to ask the token vendor project.
